package com.serhat.taskFlow.entity.enums;

public enum NotificationType {
    TASK_ASSIGNED,
    MANAGER_ASSIGNED,
    ADMIN_ASSIGNED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_COMPLETED,
    TASK_IN_PROGRESS,
    TASK_CHANGE_REQUEST,
    TASK_CHANGE_APPROVED, TASK_CHANGE_REJECTED, TASK_CHANGE_REQUEST_RESPONDED, GENERAL
}
